/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservoirsRouteImport } from './routes/reservoirs'
import { Route as PumpsRouteImport } from './routes/pumps'
import { Route as IndexRouteImport } from './routes/index'

const ReservoirsRoute = ReservoirsRouteImport.update({
  id: '/reservoirs',
  path: '/reservoirs',
  getParentRoute: () => rootRouteImport,
} as any)
const PumpsRoute = PumpsRouteImport.update({
  id: '/pumps',
  path: '/pumps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pumps': typeof PumpsRoute
  '/reservoirs': typeof ReservoirsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pumps': typeof PumpsRoute
  '/reservoirs': typeof ReservoirsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pumps': typeof PumpsRoute
  '/reservoirs': typeof ReservoirsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pumps' | '/reservoirs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pumps' | '/reservoirs'
  id: '__root__' | '/' | '/pumps' | '/reservoirs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PumpsRoute: typeof PumpsRoute
  ReservoirsRoute: typeof ReservoirsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservoirs': {
      id: '/reservoirs'
      path: '/reservoirs'
      fullPath: '/reservoirs'
      preLoaderRoute: typeof ReservoirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pumps': {
      id: '/pumps'
      path: '/pumps'
      fullPath: '/pumps'
      preLoaderRoute: typeof PumpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PumpsRoute: PumpsRoute,
  ReservoirsRoute: ReservoirsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
